@startuml
'https://plantuml.com/sequence-diagram

actor player
actor opponent
boundary api
database persistence

player -> api : /end request with reason
activate api
api -> persistence : load game
activate persistence
persistence -> api : Success
deactivate persistence

api -> persistence : delete game and players
activate persistence
persistence -> api : Success
deactivate persistence

api -> player : Success
api -> opponent : end game with reason

@enduml
