@startuml
'https://plantuml.com/sequence-diagram

actor player
actor X
actor O
boundary api
database persistence

player -> api : /start request
activate api
api -> persistence : look for earliest open game
activate persistence
persistence -> api : Success
deactivate persistence

api -> persistence : add player
activate persistence
persistence -> api : Success
deactivate persistence

alt no open game
api -> persistence : add open game
activate persistence
persistence -> api : Success
deactivate persistence
api -> player : wait for game
else
api -> persistence : close game
activate persistence
persistence -> api : Success
deactivate persistence
api -> api : determine order of play (player will be X or O)
api -> X : taketurn
api -> O : wait for game
end

@enduml
