@startuml
'https://plantuml.com/sequence-diagram

actor player
actor opponent
boundary api
database persistence

player -> api : /end request
activate api

api -> persistence : load game
activate persistence
persistence -> api : Success
deactivate persistence

api -> persistence : update game (board and turn)
activate persistence
persistence -> api : Success
deactivate persistence

api -> player : Success
api -> opponent : taketurn game

@enduml
