@startuml
'https://plantuml.com/sequence-diagram

actor A
boundary ws
actor B

A -> ws : **start** game
activate ws
ws -> A : **wait**
deactivate ws

B -> ws : **start** game
activate ws
alt A plays first (flip if B plays first)
ws -> B : **start** game << 0 >>
ws -> A : **taketurn** << X | <<board>> >>
deactivate ws
loop until **end** game
A -> ws : **taketurn** <<new board>>
activate ws
ws -> B : **taketurn** <<new board>>
deactivate ws
B -> ws : **taketurn** <<new board>>
activate ws
ws -> A : **taketurn** <<new board>>
deactivate ws
end
end
deactivate ws

alt game ends in Win/Lose/Tie (assumes A last move)
A -> ws : **end** send gameState <<Win|Lose|Tie>>
activate ws
ws -> B : **end** send gameState <<Win|Lose|Tie>>
deactivate ws
end

@enduml
