os: linux
dist: bionic
language: node_js
jobs:
  include:
  - stage: Test Pull Request
    script:
    - yarn test
    if: type = pull_request
  - stage: Deploy to Production
    script:
    - "./.travis/deploy.sh"
    if: type = push AND branch = main
addons:
  ssh_known_hosts:
  - 45.79.110.249
env:
  global:
    secure: V+xLHMbZN7IrFxW6rSQVUbVGgkmpCpRo0rJnJVUJqTyRf1IzlaZOfu2lDs+3hcrGT1MV0ANztGVZNXXesqoW85RQC6Hnd3vSqapURFUn1Ucpha8ESrE1WlbYczYH3swVFu1f3xHIPmMr2Ds9P/Hjfqhn1x4sNTQ689vJw00yHmNFSDIk0E+Gac8KSKzgek7YWbjUHLFt4f12a28YWNsjHoiL4plSeHB0BWFiizTTRQI2NS21n0ko5fX1dpRfKq7PDrnsO06fTRq1v6b4+ZqMs9srNqvq4fh3MDbcTG4unjMSeB8kOdRrb6KXGZWpyyJea2XSB8bwYFkMhIb98PsvfGeKwCMz+bWxvkTst6oxzB68jxR5vQDDchJDDt71mhgVk0xARnhk2XMDxwdAahTbocqmGH7tAb3Xqbgr/p4vweODA09PTQC2fGuLq1RoX0qqbnmpxJUQW92CyAqswRJMu9ZXFPWviD3hGQFG2ErR6yAxOfp4WN/3QXWmMl4IhgDV68fBafalR6236CTqtbCczOOboo0iEyjazDJUxdPsZfw5z1f4iJ9IjLsOeSenSHT3EENrGEO5pphq395lhCiyQ34bq1SJWGlvIBct2QhhOI2yeSKU3M3q4Sq+Hn1IrHsX4joGIrFtYXaAxN7/e4rDbvs5NFqGRMiQLFlU+vghmek=
