version: "3.8"

services:
  web:
    build:
      context: .
      args:
        APP: web
        RELEASE: ${RELEASE}
    volumes:
      - /var/cert/royhome.net:/var/cert/royk.us
      - .:/var/app/royhome-net
      - /var/app/royhome-net/node_modules
      - /var/log/royhome-net
    ports:
      - "3000:3000"
      - "9229:9229"
    extra_hosts:
      - "api.royk.us:172.17.0.1"
      - "api.royhome.net:172.17.0.1"
    network_mode: "host"
    depends_on:
      - api

  api:
    build:
      context: .
      args:
        APP: api
        RELEASE: ${RELEASE}
    volumes:
      - /var/cert/royhome.net:/var/cert/royk.us
      - .:/var/app/royhome-net
      - /var/app/royhome-net/node_modules
      - /var/log/royhome-net
    ports:
      - "5000:5000"
      - "9230:9229"
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
