@startuml
'https://plantuml.com/sequence-diagram
actor browser
participant "web-server" as ssr
database "api-server" as api
participant auth0

title load the page

== Initial time on page (no session-id) ==
autonumber 1
autoactivate on
browser -> ssr: load page - no cookies
ssr --> browser: returns html with generated browser-id and session-id cookies
autoactivate off
browser -\\ api: save session - page load and dark-mode

== login to auth0 ==
autonumber 1
autoactivate on
browser -> auth0: login to auth0
auth0 --> browser: return claim with public user data
browser -\\ api: save claim and user information
api --> browser: return

== return visit to page ==
autonumber 1
autoactivate on
browser -> ssr: load page - cookies
ssr -> api: load the session and user information
api --> ssr: return data
ssr --> browser: returns html
autoactivate off
browser -\\ api: save page load to database
alt if authenticated
browser -\\ auth0: auth0 connects, authenticates
auth0 --> browser: returns claim with user information
end

@enduml
