@startuml
'https://plantuml.com/nwdiag'

nwdiag {
  group {
    color = "lightgrey"
    router;
    sager;
    alienware;
    latitude;
  }
  inet [shape = cloud];
  inet -- router;

  network proxy {
    router [address = "8080", host = "192.168.1.1", description = "orbi"];
    sager [address = "192.168.1.42", shape = node, description = "sager\ncpu: 4\nMHz: 3000\nRAM: 8M\nHard: 128G (111G)"];
    latitude [address = "192.168.1.41", shape = node, description = "latitude\ncpu: 4\nMHz: 3300\nRAM: 8M\nHard: 768G (691G)"];
    alienware [address = "192.168.1.43", shape = node, description = "alienware\ncpu: 8\nMHz: 4000\nRAM: 8M\nHard: 1T (924G)"];
  }
}

@enduml
