@startuml
nwdiag {
  group {
    color = "lightgrey"
    router;
    web;
    api;
    db;
  }
  inet [shape = cloud];
  inet -- router;

  network proxy {
    web [address = "6000, 7000", shape = node, description = " web\n(react)"];
    router;
    api [address = "6001, 7001", shape = node, description = " api\n(kotlin)"];
  }
  network internal {
    api;
    db [shape = database, description = "postgres"];
  }
}
@enduml
