@startuml
'https://plantuml.com/ie-diagram

hide circle

entity resume {
  *resume_id : UUID
  --
  address : varchar(255)
  display_phone : boolean
  email : varchar(255)
  name : varchar(255)
  phone : varchar(255)
  summary : varchar(1024)
}
entity skill {
  *skill_id : UUID
  --
  name : varchar(255)
  position : int
}
entity skill_group {
  *skill_group_id : UUID
  --
  name : varchar(255)
  position : int
}
entity experience_description {
  *description_id : UUID <<generated>>
  --
  name : varchar(255)
  position : int
}
entity experience_bullet {
  *bullet_id : UUID <<generated>>
  --
  name : varchar(1024)
  position : int
}
entity experience {
  *experience_id : UUID <<generated>>
  --
  company : varchar(255)
  end_date : date
  start_date : date
  title : varchar(255)
  position : int
}
entity education {
  *education_id : UUID <<generated>>
  --
  degree : varchar(255)
  graduation : varchar(255)
  school : varchar(255)
  position : int
}
entity project {
  *project_id : UUID <<generated>>
  --
  name : varchar(255)
  url : varchar(255)
  description : varchar(255)
  end_date : date
  start_date : date
}

resume ||..o{ experience
resume ||..o{ skill_group
skill_group ||..o{ skill
experience ||..o{ experience_bullet
experience ||..o{ experience_description
experience ||..o{ skill_group
resume ||..o{ education
resume ||..o{ project

@enduml
