name: Deploy code

on:
  push:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Display
        run: |
          echo "$USER"
          echo "$HOST"
          echo "$KEY"
          echo "SSH_USER : ${{ env.USER }}"
          echo "SSH_HOST : ${{ env.KEY }}"
          echo "SSH_KEY : ${{ env.HOST }}"
          echo "SSH_USER : ${{ vars.USER }}"
          echo "SSH_HOST : ${{ vars.KEY }}"
          echo "SSH_KEY : ${{ vars.HOST }}"
          echo "SSH_USER : ${{ vars.SSH_USER }}"
          echo "SSH_HOST : ${{ vars.SSH_KEY }}"
          echo "SSH_KEY : ${{ vars.SSH_HOST }}"
          echo "variable from shell environment : $env_var"
        env:
          USER: ${{ vars.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY2 }}
          HOST: ${{ env.env_var }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ vars.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: $env_var

      - name: Stop the server
        run: ssh staging 'ls -l && pwd'
