name: Deploy code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Configure SSH for ${{ env.USER }}@${{ env.HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "${{ env.KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ env.HOST }}
            User ${{ env.USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          USER: ${{ vars.SSH_USER }}
          HOST: ${{ vars.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: ssh staging '/usr/royhome/scripts/deploy/deploy-release.sh web'
