name: Deploy code

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Configure SSH for ${{ env.USER }}@${{ env.HOST }}
        run: |
          echo "Adding SSH_KEY for deployment to ${{ env.USER }}@${{ env.HOST }}
          mkdir -p ~/.ssh/
          rm -f  ~/.ssh/staging.key
          echo "${{ env.KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName ${{ env.HOST }}
            User ${{ env.USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          USER: ${{ vars.SSH_USER }}
          HOST: ${{ vars.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}

      - name: Stop the server
        run: ssh staging 'ls -la'
